{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ .path }}
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
{{- end }}
