---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: photoprism

resources:
  - namespace.yaml

helmCharts:
  - name: photoprism
    repo: https://andrenarchy.github.io/helm-charts/
    releaseName: photoprism
    version: 8.11.0
    includeCRDs: true
    namespace: photoprism
    valuesFile: ./values.yaml
