persistence:
  config:
    enabled: false
  originals:
    enabled: false
  import:
    enabled: false
  backup:
    enabled: false

mariadb:
  enabled: false

# env:
#   PHOTOPRISM_ADMIN_PASSWORD:
#     valueFrom:
#       secretKeyRef:
#         name: photoprism-secrets
#         key: PHOTOPRISM_ADMIN_PASSWORD
#   PHOTOPRISM_DATABASE_PASSWORD:
#     valueFrom:
#       secretKeyRef:
#         name: photoprism-secrets
#         key: PHOTOPRISM_DATABASE_PASSWORD
