spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mkoelle/homelab.git
    targetRevision: HEAD

applications:
  - name: cilium
    project: default
    path: apps/core/cilium
    namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: argocd
    project: default
    path: apps/core/argocd
    namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: photoprism
    project: default
    path: apps/media/photoprism
    namespace: photoprism
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: paperless-ngx
    project: default
    path: apps/productivity/paperless-ngx
    namespace: paperless
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
