---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd
  namespace: core-argocd
  # finalizers: [resources-finalizer.argocd.argoproj.io]

spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.1.3
    helm:
      parameters:
        - name: server.config.kustomize\.buildOptions
          value: --enable-helm
      values: |
        server:
          config:
            kustomize.buildOptions: "--enable-helm"
  destination:
    server: https://kubernetes.default.svc
    namespace: core-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
  # ignoreDifferences:
  #   - group: argoproj.io
  #     kind: Application
  #     jsonPointers: [/status]
