---
files: ['**', .*/**]
useGitignore: true
ignorePaths: [.git, .build, charts]

dictionaryDefinitions:
  - name: myWords
    path: ./cSpell_dict.txt
    addWords: true
  - name: namesUsersAndProducts
    path: ./cSpell_names_products.txt
    addWords: true

dictionaries: [myWords, namesUsersAndProducts]
